name: Check

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: build
        run: yarn install && make build
        env:
          CI: true
      - name: lint
        run: make lint
        env:
          CI: true
      - name: test
        run: yarn run jest --ci
        env:
          CI: true
